### PR TITLE
Chinese translations

### PR DESCRIPTION
**Pull request by Snapshotlight**
I translated them into Chinese. Enjoy it!

### CODE REVIEW

**Comment by orangeadam3** [comment]
Cool, I've been hoping people would add some translations, to other languages. Thank You. You are fluent in Chinese correct? I don't want it to just be google translate or something.

**Comment by Snapshotlight** [comment]
> Cool, I've been hoping people would add some translations, to other languages. Thank You. You are fluent in Chinese correct? I don't want it to just be google translate or something.

Of course not. I am a Chinese and I think your mod is cool so I translated your mod into Chinese. Thank you for accepting my tranlation.

**Comment by orangeadam3** [comment]
Cool. That's all the confirmation I needed. Please understand that I have heard of people submitting translations they did with google translate while thinking they are helping.

**Comment by orangeadam3** [comment]
Thank you for your contribution.

**Comment by Snapshotlight** [comment]
uh, some questions. What is the use of "smooth blending" ? I can't understand what it means only through text

**Comment by Snapshotlight** [comment]
btw, what is the meaning of "Airocean"? Is that a way of Projection (However, I could not find any information about it :(
and what's BTE?
I will be appreciated if you can answer me

**Comment by ChasmSolacer** [comment]
> btw, what is the meaning of "Airocean"? Is that a way of Projection (However, I could not find any information about it :(
> and what's BTE?

Airocean is the Dymaxion projection (or a variation of it). I translated it into Fuller (not BTE) since the word _dymaxion_ isn't translatable into my language. BTE means Build The Earth, it's recommended to translate terra121.projection.bteairocean into Build The Earth

**Pull request merged**
