### PR TITLE
Update road generation

### PR DESCRIPTION
**Pull request by taeko-chan**
The goal is to better reflect the width of the roads in the real world.
This is the base for what is planned to add actual tunnels as well as bridges.

So yeah, I'm very open to feedback, and I'm excited about the future of Terra 1:1!

### CODE REVIEW

**Comment by LittlePippy** [comment]
i was a bit sad to see the roads unnoticably small so this is a great step it seems. thank you very much. also how would tunnels work? would they just be some way to make roads disappear or could they actually work as real or minecraft tunnels?

**Comment by orangeadam3** [comment]
Yeah its logical to have upright as default however the only reason is for back compatibility since flipped used to be the only option in earlier versions. If you dont use customize world minecraft saves the generator settings as "". Quite annoyingly, so the defaults have to always be the same otherwise someone could update the mod, load into their pre-existing world and suddenly the terrain around their base becomes an ocean on the other side of the world. 

I could mabye try to detect the version of the mod it was created in to figure out the defaults but, I'm not sure if that is possible.

The other changes look promising and I suppose if you change roads too much I can just add it as another option in customize world.

**Comment by orangeadam3** [comment]
Also, I'm not sure but I want to say all OSM tunnels also have a level flag and If you just had a short or a byte containing the level it could take up less memory and be used for bridges later on.
Also my excuse for this file being disgusting is that I had to overhaul it like 2 times to support new functionality.

**Comment by taeko-chan** [comment]
ok here's what i'll do:
i'll pull the newer version so riverState is included
i'll add the level from OSM as a Byte
and i'll also wrap the else ifs with highway != null in a single statement.
I'll update the pull request in a few hours

**Comment by taeko-chan** [comment]
alrighty, i fixed some stuff, added layers (somewhat) and got rid of that highway != null thing. should be better now!
at the moment, roads will only generate if they are layer 1 from osm, so no tunnels and bridges

**Comment by taeko-chan** [comment]
merged orangeadam3/terra121 with my fork to update the pull request to include the newest commit

**Comment by orangeadam3** [comment]
Ok, looks good. I'm a little conflicted about not showing bridges and there are some efficiency fixes that could probably be added, but this is all stuff that could be done after a merge. Now that the official release is out things can get more experimental. I'm gonna have @shejan0 take a look to make sure there weren't any unintended consequences, but other than that I'm almost ready to merge.

**Comment by orangeadam3** [comment]
Looks good, @shejan0 took a look at it. Ill merge tomorrow so I can see any fallout while I'm awake.

**Comment by taeko-chan** [comment]
ok, great! now that it's the weekend, i'll have more time to work on the levels + experiment with neural nets to see if i can solve issue #39 about the flat roads.
I think it may be possible to group divided highways by their relations on OSM, for instance a freeway "A2" with 2 separate roads would have tons and tons of members (A2 whatever), but each member would belong too the relation A2.

**Comment by orangeadam3** [comment]
Don't change too much in that area yet. I plan to do fix the multipoly buildings bug and try to adress the grounding errors where evreything gets covered in water today.

**Comment by orangeadam3** [comment]
Also be careful with bloat. More features can be cool but it shouldn't come at the cost of efficiency or complicated code. I was thinking about using neural networks for biome classification. So if you do make a class make sure it can be used on other things.

**Comment by orangeadam3** [comment]
Cleaned OSM code and changed road classification (all credit to taeko-chan)

**Comment by taeko-chan** [comment]
ok, good idea.
i'll make the nn so it's fairly general use.
I see what you mean about bloat, for the time being i'll just do some experiments on my personal machine to see what's possible without pushing them to my fork, or if i do i'll make a new branch. Obviously you'll get to say if you think they're something that should be implemented or not

**Pull request merged**
