### PR TITLE
Rename pl-pl.lang to pl_pl.lang

### PR DESCRIPTION
**Pull request by ChasmSolacer**

### CODE REVIEW

**Comment by ChasmSolacer** [comment]
Please notice that in Polish and German (and possibly many other languages) the button labels are too wide:
image

**Comment by orangeadam3** [comment]
Does the name matter? But yeah the label thing is an issue, mabye I could just remove (experimental) for those langs

**Comment by ChasmSolacer** [comment]
The file name matters a lot, it must be pl_pl.lang in order to add Polish translation. I made a typo before

**Comment by ChasmSolacer** [comment]
The same thing is with the Ukrainian (in [#68](https://github.com/orangeadam3/terra121/pull/68))

**Comment by Blueberryy** [comment]
Careful with file name next time

**Pull request merged**
