### PR TITLE
updating translations

### PR DESCRIPTION
**Pull request by Snapshotlight**
as the title said.

### CODE REVIEW

**Comment by Snapshotlight** [comment]
Sorry, I don't know how to update files.

**Comment by orangeadam3** [comment]
I can add those translations to the file myself in a few hours, if you can't get it to work.

**Comment by Snapshotlight** [comment]
Nothing. I am trying to update files.

**Comment by Snapshotlight** [comment]
It seems that I need your help to update translations. I am sorry.

**Comment by Snapshotlight** [comment]
I'll reopen it then. However, I changed en_us.lang file by mistake. Sorry.

**Comment by Snapshotlight** [comment]
Oh, it seemed that the conflicts is resolved.

**Comment by orangeadam3** [comment]
It says you are trying to change the en_us file. I think this is a mistake. Copy the file from my latest commit to use or disregard the change. Also putting "#PARSE_ESCAPES" as the first line will let the "\n" work properly, but I can add that if you don't want to deal with it.

**Comment by Snapshotlight** [comment]
Yes, the change of the en_us file was a mistake. I will try to deal with it. Thank you a lot.

**Comment by Snapshotlight** [comment]
Well, I have copied it. But I don't know if it will be alright.

**Comment by orangeadam3** [comment]
More or less fixed it. Probably fine

**Pull request merged**
